### PR TITLE
Allows lifetime elision and removes casting

### PR DESCRIPTION
**Pull request by lucasloisp**
Simple changes guided by clippy

### CODE REVIEW

**Comment by quadrupleslap** [comment]
The "add" looks good but are you sure the elision is equivalent? I put that in their to basically work as a mutex on the capturer.

**Comment by lucasloisp** [comment]
To be honest I was guided by clippy to make that change. But, as seen on the rustonomicon, 

"If there is exactly one input lifetime position (elided or not), that lifetime is assigned to all elided output lifetimes."

```rust
fn new(buf: &mut [u8]) -> BufWriter;                    // elided
fn new<'a>(buf: &'a mut [u8]) -> BufWriter<'a>```

**Comment by lucasloisp** [comment]
What I could try out is removing the 'b annotation on the output to ensure it is the same as the one on the Input (as it was originally)

**Comment by owenthewizard** [comment]
What's holding this from being merged?

**Pull request closed without merging**
